---

name: Go

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: go.mod tidy
        run: go mod tidy && git diff --exit-code

      - name: license header
        run: go run github.com/elastic/go-licenser@v0.4.1 -d
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Test
        run: go test ./...
